name: Deploy GitHub pages

env:
  NODE_VERSION: 20
  GH_PAGES_DIR: gh-pages-dist

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # with:
        #   persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm ci --no-audit --no-progress
      - name: Build
        run: npm run build -- --env out=$GH_PAGES_DIR
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: ${{ env.GH_PAGES_DIR }} # The folder the action should deploy.
          clean: true
